#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  touchSensL,     sensorTouch)
#pragma config(Sensor, dgtl2,  touchSensR,     sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           driveLeftBack, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           driveLeftFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLBot,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armRBot,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveRightBack, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port9,           driveRightFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          knock,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify
#include "Starstruck.h"

//CONSTANTS
#define LOOPSPEED 50 //Time between user control loops in milliseconds - time alloted to other tasks while usercontrol is idle
#define DEADZONE 20 //Deadzone for joystick control

//GLOBAL VARIABLES
float powerExpanderBatteryV;
//Control variables
int dlC, drC, armC, knockC, forwardsC, backwardsC, touchSensLC, touchSensRC;
float armMultiplier, dMult = 1;

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

	bStopTasksBetweenModes = true;
}

task autonomous()
{
	//autonSelector();
}


task usercontrol()
{

	//Math variables
	int lastArmC, currArmC;
	while(true){
		dlC = vexRT[Ch3];
		drC = vexRT[Ch2];
		armC = vexRT[Ch2Xmtr2];
		knockC = vexRT[Ch3Xmtr2];
		forwardsC = vexRT[Btn7U];
		backwardsC = vexRT[Btn7D];
		touchSensRC = SensorValue[touchSensL];
		touchSensLC = SensorValue[touchSensR];
		if(forwardsC == 1) {
			dMult = 1;
		} else if(backwardsC == 1) {
			dMult = -1;
		}

		if(abs(dlC) > DEADZONE)	{
			motor[driveLeftBack] = dlC * dMult;
			motor[driveLeftFront] = dlC * dMult;
		}
		else {
			motor[driveLeftBack] = 0;
			motor[driveLeftFront] = 0;
		}
		if(abs(drC) > DEADZONE)	{
			motor[driveRightBack] = drC * dMult;
			motor[driveRightFront] = drC * dMult;
		}
		else {
			motor[driveRightBack] = 0;
			motor[driveRightFront] = 0;
		}

		lastArmC = currArmC;
		currArmC = armC;

		if((touchSensLC == 1 || touchSensRC == 1) & armC > 0) {
			motor[armLTop] = 0;
			motor[armLBot] = 0;
			motor[armRTop] = 0;
			motor[armRBot] = 0;
		} else if(abs(armC) > DEADZONE)	{
			motor[armLTop] = armC;
			motor[armLBot] = armC;
			motor[armRTop] = armC;
			motor[armRBot] = armC;
	  } else {
			motor[armLTop] = 0;
			motor[armLBot] = 0;
			motor[armRTop] = 0;
			motor[armRBot] = 0;
		}


		if(abs(knockC) > DEADZONE)	{
			motor[knock] = knockC;
		}
		else {
			motor[knock] = 0;
		}
		//Displays Battery Levels to VEX Remote Screen
		powerExpanderBatteryV = SensorValue[in1]/.28;
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDPos(0,0);
		displayNextLCDString("C Bat:");
		displayNextLCDNumber(nAvgBatteryLevel);
		displayLCDPos(1,0);
		displayNextLCDString("P.E Bat:");
		displayNextLCDNumber(powerExpanderBatteryV);

		wait1Msec(LOOPSPEED);
	}
}
