#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  armButton,      sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           clawL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           dLeftF,        tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port3,           dLeftB,        tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port4,           armL1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armL2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armR1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           dRightF,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port9,           dRightB,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          clawR,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// to turn left, motors are negative
//to turn right, motors are positive


/* NOTES

Potentiometer key:
Closed: ~3900
180 Degrees: ~2660
45 degrees (facing towards stars but not closed): ~1700
Fully closed: ~1000, 1100



*/



#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#define LOOPSPEED 50 //Time between user control loops in milliseconds - time alloted to other tasks while usercontrol is idle
#define DEADZONE 30 //Deadzone for joystick control
#define m_clawL 1
#define m_dLeftF 2
#define m_dLeftB 3
#define m_armL1 4
#define m_armL2 5
#define m_armR1 6
#define m_armR2 7
#define m_dRightF 8
#define m_dRightB 9
#define m_clawR 10

#define joy_left_vertical "ch3Xmtr2"
#define joy_left_horizontal "ch4Xmtr2"
#define joy_right_vertical "ch2Xmtr2"
#define joy_right_horizontal "ch1Xmtr2"

//GLOBAL VARIABLES
float powerExpanderBatteryV;
//Control variables
int overFence, armC, armUp,armDown, rotateRight, rotateLeft, clawC,musicCtrl, openSlow, openFast, closeSlow, closeFast, direction=1, ChangeControl;
int armMotors;
unsigned int beat = 0;

#include "Vex_Competition_Includes.c"

//#include "music.h"


#include "StarstruckIncludes.h"
//#include "motor.c"





void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

	bStopTasksBetweenModes = true;
}

void halfOpenClaw()
{
	while(SensorValue(pot) < 2500 || SensorValue(pot) > 2800)
	{
		if(SensorValue(pot) < 2500)
		{
			motor[clawL] = -50;
			motor[clawR] = -50;
			wait1Msec(50);
		}
		if(SensorValue(pot) > 2800)
	{
		motor[clawL] = 50;
			motor[clawR] = 50;
			wait1Msec(50);
	}
}
wait1Msec(200);

while(SensorValue(pot) < 2500 || SensorValue(pot) > 2800)
	{
		if(SensorValue(pot) < 2500)
		{
			motor[clawL] = -50;
			motor[clawR] = -50;
			wait1Msec(50);
		}
		if(SensorValue(pot) > 2800)
	{
		motor[clawL] = 50;
			motor[clawR] = 50;
			wait1Msec(50);
	}
}
}

/*
	while(SensorValue(pot)<2660)
	{
		motorclawL=-50;
		wait1MSec(50);
		if (Sensor
}
*/

void armRotationUser(int r)
{
	int counter=0;
	while(SensorValue(armEncoder) < r-24 || SensorValue(armEncoder) > r+24)
	{

		if(SensorValue(armEncoder) < r-24)
		{
			motor[armL1] = -50;
			motor[armL2] = -50;
			motor[armR1] = -50;
			motor[armR2] = -50;
			wait1Msec(50);
		}
		else if(SensorValue(armEncoder) > r+24)
	{
			motor[armL1] = 50;
			motor[armL2] = 50;
			motor[armR1] = 50;
			motor[armR2] = 50;

			wait1Msec(50);
	}
		if (counter>=r-40)
	{
		motor[clawR] = 20;
		motor[clawL]=20;
		wait1Msec(50);
}
	counter+=1;

}
}

void armRotation(int r)
{
	int counter=0;
	while(SensorValue(armEncoder) < r-24 || SensorValue(armEncoder) > r+24)
	{

		if(SensorValue(armEncoder) < r-24)
		{
			motor[armL1] = -50;
			motor[armL2] = -50;
			motor[armR1] = -50;
			motor[armR2] = -50;
			wait1Msec(500)
		}

		if(SensorValue(armEncoder) > r+24)
	{
			motor[armL1] = 50;
			motor[armL2] = 50;
			motor[armR1] = 50;
			motor[armR2] = 50;

			wait1Msec(500);
	}
	counter+=1;

}
}

void auton1() {


	motor[clawR] = 70;
	motor[clawL]= 70;
	wait1Msec(1500);
	motor[clawR] = 0;
	motor[clawL] = 0;

	motor[armL1] = 100;
	motor[armL2] = 100;
	motor[armR1] = 100;
	motor[armR2] = 100;
	wait1Msec(2000);
	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;

	motor[dLeftB] = 70;
	motor[dRightB] = 70;
	motor[dLeftF] = 70;
	motor[dRightF] = 70;
	wait1Msec(1700);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;

	motor[dLeftB] = -50;
	wait1Msec(200);
	motor[dRightB] = 50;
	wait1Msec(200);
	motor[dLeftF] = 50;
	wait1Msec(200);
	motor[dRightF] = 50;
	wait1Msec(5000);
	halfOpenClaw();
	armRotation(-256);

	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
	motor[clawL] = 0;
	motor[clawR] = 0;
	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;
}
/*
void auton2() {

	motor[dLeftB] = 70;
	motor[dRightB] = 70;
	motor[dLeftF] = 70;
	motor[dRightF] = 70;
	wait1Msec(3000);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
}
*/



void auton3(){
/*
	//halfOpenClaw();
	motor[clawL] = 0;
	motor[clawR] = 0;
	armRotation(-256);

	motor[dLeftB] = -50;
	motor[dRightB] = 50;
	motor[dLeftF] = 50;
	motor[dRightF] = -50;
	wait1Msec(2500);



	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;

	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;

*/
/*
while(SensorValue(pot) < 2500 || SensorValue(pot) > 2800)
	{
		if(SensorValue(pot) > 2400)
		{
			motor[clawL] = -50;
			motor[clawR] = -50;
			wait1Msec(50);
		}

		else if(SensorValue(pot) < 2700)
	{
		motor[clawL] = 50;
			motor[clawR] = 50;
			wait1Msec(50);
	}
	motor[clawL] = 0;
motor[clawR] = 0;
}
motor[clawL] = 0;
motor[clawR] = 0;
wait1Msec(200);

while(SensorValue(pot) < 2500 || SensorValue(pot) > 2800)
	{
		if(SensorValue(pot) < 2500)
		{
			motor[clawL] = -50;
			motor[clawR] = -50;
			wait1Msec(50);
		}

		else if(SensorValue(pot) > 2800)
	{
		motor[clawL] = 50;
			motor[clawR] = 50;
			wait1Msec(50);
	}
	motor[clawL] = 0;
motor[clawR] = 0;
}
motor[clawL] = 0;
motor[clawR] = 0;
*/
halfOpenClaw();
int r = -200;
while(SensorValue(armEncoder) < r-24 || SensorValue(armEncoder) > r+24)
	{

		if(SensorValue(armEncoder) < r-24)
		{
			motor[armL1] = -50;
			motor[armL2] = -50;
			motor[armR1] = -50;
			motor[armR2] = -50;
			wait1Msec(500);
		}

		else if(SensorValue(armEncoder) > r+24)
	{
			motor[armL1] = 50;
			motor[armL2] = 50;
			motor[armR1] = 50;
			motor[armR2] = 50;

			wait1Msec(500);
	}
	wait1Msec(1000);
	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;

	motor[dLeftB] = -80;
	motor[dRightB] = -80;
	motor[dLeftF] = -80;
	motor[dRightF] = -80;
	wait1Msec(2000);



	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;

}}

task autonomous()
{
	/*
	motor[dLeftB] = 127;
	motor[dRightB] = 127;
	motor[dLeftF] = 127;
	motor[dRightF] = 127;
	wait1Msec(4000);
	motor[dLeftB] = -127;
	motor[dRightB] = -50;
	motor[dLeftF] = -127;
	motor[dRightF] = -50;
	wait1Msec(1000);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
	*/
/*
	motor[dLeftB] = 50;
	motor[dRightB] = -50;
	motor[dLeftF] = 50;
	motor[dRightF] = -50;
	wait1Msec(5000);
	halfOpenClaw();
	armRotation(-256);

	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
	motor[clawL] = 0;
	motor[clawR] = 0;
	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;
	*/
auton3();
}

task nonMusic() {
	nSchedulePriority = 10;
	//Math variables

	int mReqD1, mReqD2, mReqD3, mReqD4, clawValue;
	while(true){

		//int joyLV = vexRT[ch3Xmtr2];
		//int joyLH = vexRT[ch4Xmtr2];
		//int joyRV = vexRT[ch2Xmtr2];
		//int joyRH = vexRT[ch1Xmtr2];

		armC = vexRT[ch2Xmtr2];
		openSlow = vexRT[Btn6UXmtr2] * 80;
		closeSlow = vexRT[Btn6DXmtr2] * -80;
//		openFast = vexRT[Btn5U] * 120;
//		closeFast = vexRT[Btn5D] * -120;
		clawC = vexRT[ch1Xmtr2];
		armUp = vexRT[Btn5UXmtr2];
		armDown = vexRT[Btn5DXmtr2];
		ChangeControl = vexRT(Btn7LXmtr2);
		overFence = vexRT(Btn8LXmtr2);
		//rotateRight = vexRT[Btn5U];
		//rotateLeft = vexRT[Btn5D];

		//musicCtrl = vexRT[Btn7UXmtr2];

		if(ChangeControl==1)
	{
		direction*=-1;
		wait1Msec(200);
	}
	if (overFence==1)
	{
		armRotationUser(-180);
}
	mReqD1 = (vexRT[ch3Xmtr2]*direction + vexRT[ch1Xmtr2]*.5 + vexRT[ch4Xmtr2]*direction);
	mReqD2 = (vexRT[ch3Xmtr2]*direction - vexRT[ch1Xmtr2]*.5 - vexRT[ch4Xmtr2]*direction);
	mReqD3 = (vexRT[ch3Xmtr2]*direction + vexRT[ch1Xmtr2]*.5 - vexRT[ch4Xmtr2]*direction);
	mReqD4 = (vexRT[ch3Xmtr2]*direction - vexRT[ch1Xmtr2]*.5 + vexRT[ch4Xmtr2]*direction);

	if(abs(mReqD1) > DEADZONE)
		motor[dLeftF] = mReqD1;
	else
		motor[dLeftF] = 0;

	if(abs(mReqD2) > DEADZONE)
		motor[dRightF] = mReqD2;
	else
		motor[dRightF] = 0;

	if(abs(mReqD3) > DEADZONE)
		motor[dLeftB] = mReqD3 ;
	else
		motor[dLeftB] = 0;

	if(abs(mReqD4) > DEADZONE)
		motor[dRightB] = mReqD4;
	else
		motor[dRightB] = 0;


	/*
			if(ChangeControl==1)
	{
		direction*=-1;
		wait1Msec(200);
	}
	mReqD1 = (vexRT[ch3Xmtr2] + vexRT[ch1Xmtr2] + vexRT[ch4Xmtr2]);
	mReqD2 = (vexRT[ch3Xmtr2] - vexRT[ch1Xmtr2] - vexRT[ch4Xmtr2]);
	mReqD3 = (vexRT[ch3Xmtr2] + vexRT[ch1Xmtr2] - vexRT[ch4Xmtr2]);
	mReqD4 = (vexRT[ch3Xmtr2] - vexRT[ch1Xmtr2] + vexRT[ch4Xmtr2]);

	if(abs(mReqD1) > DEADZONE)
		motor[dLeftF] = mReqD1 * direction;
	else
		motor[dLeftF] = 0;

	if(abs(mReqD2) > DEADZONE)
		motor[dRightF] = mReqD2 * direction;
	else
		motor[dRightF] = 0;

	if(abs(mReqD3) > DEADZONE)
		motor[dLeftB] = mReqD3 * direction ;
	else
		motor[dLeftB] = 0;

	if(abs(mReqD4) > DEADZONE)
		motor[dRightB] = mReqD4 * direction;
	else
		motor[dRightB] = 0;
	*/
		if(SensorValue(armButton) == 1) {
			SensorValue(armEncoder) = 0;
		}
	//	if((abs(armC) > DEADZONE)&& (SensorValue(armButton) == 0 || armC > 0)) {
		//	armMotors =armC;
		//} else {
		//	armMotors = 0;
		//}

		if(armUp==1)
	{
		armMotors=80;
	}

		else if((armDown==1))
	{
		armMotors=-80;
	}
		else
	{
		armMotors=0;
	}



		clawValue = openSlow + closeSlow + openFast + closeFast;
		motor[clawL] = clawValue;
		motor[clawR] = clawValue;

		//Set Motors
		motor[armL1] = armMotors;
		motor[armL2] = armMotors;
		motor[armR1] = armMotors;
		motor[armR2] = armMotors;




		//Displays Battery Levels to VEX Remote Screen
		powerExpanderBatteryV = SensorValue[in1]/.28;
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDPos(0,0);
		displayNextLCDString("C Bat:");
		displayNextLCDNumber(nAvgBatteryLevel);
		displayLCDPos(1,0);
		displayNextLCDString("P.E Bat:");
		displayNextLCDNumber(powerExpanderBatteryV);

		//if(vexRT[Btn8UXmtr2] == 1) {
		//	auton1();
		//}
/*
		if(vexRT[Btn8DXmtr2] == 1) {
			auton2();
		}
		*/
		if(vexRT[Btn7UXmtr2] == 1)
		{
			halfOpenClaw();
		}

		datalogDataGroupStart();
		datalogAddValue(0, mReqD1);
		datalogAddValue(1, mReqD2);
		datalogAddValue(2, mReqD3);
		datalogAddValue(3, mReqD4);
		datalogDataGroupEnd();

		wait1Msec(LOOPSPEED);
	}
}



task usercontrol()
{
	//startTask(music);
	startTask(nonMusic);
	//startTask(motorSlew);
}
