#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    potCL,          sensorPotentiometer)
#pragma config(Sensor, in2,    potCR,          sensorPotentiometer)
#pragma config(Sensor, dgtl6,  quadL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  quadR,          sensorQuadEncoder)
#pragma config(Motor,  port1,           clawL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           dLeftF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           dLeftB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armL1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armR1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armR2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           dRightF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           dRightB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          clawR,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// to turn left, motors are negative
//to turn right, motors are positive


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#define LOOPSPEED 50 //Time between user control loops in milliseconds - time alloted to other tasks while usercontrol is idle
#define DEADZONE 20 //Deadzone for joystick control
#define m_clawL 1
#define m_dLeftF 2
#define m_dLeftB 3
#define m_armL1 4
#define m_armL2 5
#define m_armR1 6
#define m_armR2 7
#define m_dRightF 8
#define m_dRightB 9
#define m_clawR 10

#define joy_left_vertical "Ch3"
#define joy_left_horizontal "Ch4"
#define joy_right_vertical "Ch2"
#define joy_right_horizontal "Ch1"

//GLOBAL VARIABLES
float powerExpanderBatteryV;
//Control variables
int armC, clawC,musicCtrl, openSlow, openFast, closeSlow, closeFast;
int armMotors;
unsigned int beat = 0;

#include "Vex_Competition_Includes.c"

//#include "music.h"


#include "StarstruckIncludes.h"
//#include "motor.c"





void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.

	bStopTasksBetweenModes = true;
}

void auton1() {

	motor[clawR] = 70;
	motor[clawL]= 70;
	wait1Msec(1500);
	motor[clawR] = 0;
	motor[clawL] = 0;

	motor[armL1] = 100;
	motor[armL2] = 100;
	motor[armR1] = 100;
	motor[armR2] = 100;
	wait1Msec(2000);
	motor[armL1] = 0;
	motor[armL2] = 0;
	motor[armR1] = 0;
	motor[armR2] = 0;

	motor[dLeftB] = 70;
	motor[dRightB] = 70;
	motor[dLeftF] = 70;
	motor[dRightF] = 70;
	wait1Msec(1700);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
}

void auton2() {
	motor[dLeftB] = 70;
	motor[dRightB] = 70;
	motor[dLeftF] = 70;
	motor[dRightF] = 70;
	wait1Msec(3000);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
}

task autonomous()
{
	motor[dLeftB] = 127;
	motor[dRightB] = 127;
	motor[dLeftF] = 127;
	motor[dRightF] = 127;
	wait1Msec(4000);
	motor[dLeftB] = -127;
	motor[dRightB] = -50;
	motor[dLeftF] = -127;
	motor[dRightF] = -50;
	wait1Msec(1000);
	motor[dLeftB] = 0;
	motor[dRightB] = 0;
	motor[dLeftF] = 0;
	motor[dRightF] = 0;
}

task nonMusic() {
	nSchedulePriority = 10;
	//Math variables

	int mReqD1, mReqD2, mReqD3, mReqD4, clawValue;
	while(true){

		//int joyLV = vexRT[Ch3];
		//int joyLH = vexRT[Ch4];
		//int joyRV = vexRT[Ch2];
		//int joyRH = vexRT[Ch1];

		armC = vexRT[Ch2];
		openSlow = vexRT[Btn6U] * 80;
		closeSlow = vexRT[Btn6D] * -80;
		openFast = vexRT[Btn5U] * 120;
		closeFast = vexRT[Btn5D] * -120;
		clawC = vexRT[Ch1];


		musicCtrl = vexRT[Btn7UXmtr2];

	mReqD1 = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
	mReqD2 = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
	mReqD3 = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
	mReqD4 = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];

	if(abs(mReqD1) > DEADZONE)
		motor[dLeftF] = mReqD1;
	else
		motor[dLeftF] = 0;

	if(abs(mReqD2) > DEADZONE)
		motor[dRightF] = mReqD2;
	else
		motor[dRightF] = 0;

	if(abs(mReqD3) > DEADZONE)
		motor[dLeftB] = mReqD3;
	else
		motor[dLeftB] = 0;

	if(abs(mReqD4) > DEADZONE)
		motor[dRightB] = mReqD4;
	else
		motor[dRightB] = 0;


		if(abs(armC) > DEADZONE) {
			armMotors = armC;
			} else {
			armMotors = 0;
		}


		clawValue = openSlow + closeSlow + openFast + closeFast;
		motor[clawL] = clawValue;
		motor[clawR] = clawValue;

		//Set Motors
		motor[armL1] = armMotors;
		motor[armL2] = armMotors;
		motor[armR1] = armMotors;
		motor[armR2] = armMotors;



		//Displays Battery Levels to VEX Remote Screen
		powerExpanderBatteryV = SensorValue[in1]/.28;
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDPos(0,0);
		displayNextLCDString("C Bat:");
		displayNextLCDNumber(nAvgBatteryLevel);
		displayLCDPos(1,0);
		displayNextLCDString("P.E Bat:");
		displayNextLCDNumber(powerExpanderBatteryV);

		if(vexRT[Btn8UXmtr2] == 1) {
			auton1();
		}

		if(vexRT[Btn8DXmtr2] == 1) {
			auton2();
		}
		wait1Msec(LOOPSPEED);
	}
}



task usercontrol()
{
	//startTask(music);
	startTask(nonMusic);
	//startTask(motorSlew);
}
