//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef MOTORC
#define MOTORC

#define MOTOR_MAX_VALUE 127
#define MOTOR_MIN_VALUE -127
#define slew 10


int armReq;
int armCur;

void reqArm(int port, int power);
void setArm(int armPower);

task armSlewControl() {
	int diff = 0;
	while(true) {
			diff = armReq - armCur;

			if(armCur < armReq) {
				armCur += (0.4*abs(diff));
			} else if(armCur > armReq) {
				armCur -= (0.4*abs(diff));
			}

			if(motorReq == 0) {
				setArm(0);
			} else if(abs(power) < MOTOR_MAX_VALUE) {
				if(armCur > 90) {
					setArm(120);
				} else {
					setArm(armCur);
				}
			}
			wait1Msec(LOOPSPEED*3);
	}
}

void setArm(int armPower) {
	motor[armL1] = armPower;
	motor[armL2] = armPower;
	motor[armR1] = armPower;
	motor[armR2] = armPower;
}

void reqArm(int power) {
	armReq = power;
}

/*
task pidController()
{
	startTask(music, 4);
	float pidErrorL;
	float pidLastErrorL;
	float pidIntegralL;
	float pidDerivativeL;

	float pidErrorR;
	float pidLastErrorR;
	float pidIntegralR;
	float pidDerivativeR;

	pidLastErrorL = 0;
	pidIntegralL = 0;

	pidLastErrorR = 0;
	pidIntegralR = 0;

	while (true)
	{
		if(flyStartup == 1 && (flyVelocityR>requestedShooterSpeed))
			flyStartup = 0;
		else if(flyStartup==0)
			pidSelect();

		pidErrorL = requestedShooterSpeed-flyVelocityL;

		if(pid_Ki!=0)
		{
			if(fabs(pidErrorL) < PID_INTEGRAL_LIMIT)
				pidIntegralL = pidIntegralL + pidErrorL;
			else
				pidIntegralL = 0;
		}
		else
			pidIntegralL = 0;
		if(pidErrorL !=0)
		{
			pidDerivativeL = pidErrorL - pidLastErrorL;
			pidLastErrorL = pidErrorL;
		}
		else
		{
			pidDerivativeL = 0;
		}
		if(pidErrorL < 4.0)
		{
			pidIntegralL = 0;
		}
		pidDriveL+= (pid_Kp*pidErrorL) + (pid_Ki*pidIntegralL) + (pid_Kd * pidDerivativeL);

		if(pidDriveL > PID_DRIVE_MAX)
			pidDriveL = PID_DRIVE_MAX;
		if(pidDriveL < PID_DRIVE_MIN)
			pidDriveL = PID_DRIVE_MIN;

} */





























#endif
